# Generated by Django 4.1 on 2022-09-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sites',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('site_url', models.CharField(max_length=50)),
                ('cipher', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
    ]
