# Generated by Django 4.0.3 on 2022-09-06 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0003_alter_sites_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='sites',
            name='cipher',
        ),
        migrations.AddField(
            model_name='sites',
            name='pages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitehandler.page'),
        ),
    ]
