# Generated by Django 4.0.3 on 2022-09-07 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0005_alter_sites_created_on_alter_sites_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sites',
            name='pages',
        ),
        migrations.AddField(
            model_name='page',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitehandler.sites'),
        ),
    ]
