# Generated by Django 4.0.3 on 2022-09-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0006_remove_sites_pages_page_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='validator',
            field=models.TextField(blank=True, null=True),
        ),
    ]
