# Generated by Django 4.1 on 2023-03-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0007_sites_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.TextField(default='tab name'),
        ),
    ]
