# Generated by Django 4.1 on 2023-03-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0008_page_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='title',
        ),
        migrations.AddField(
            model_name='sites',
            name='title',
            field=models.TextField(default='Title'),
        ),
    ]
